export const USER_INPUT_LOGIN_CHANGED = 'USER_INPUT_LOGIN_CHANGED';
export const USER_TRY_TO_LOG_IN = 'USER_TRY_TO_LOG_IN';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

//search constants
export const SEARCH_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE';
export const SEARCH_LOADER = 'SEARCH_LOADER';
export const MAKE_SEARCH_SUCCESS = 'MAKE_SEARCH_SUCCESS';
export const MAKE_SEARCH_FAILED = 'MAKE_SEARCH_FAILED';
